### ISSUE TITLE
[OldUpload] [BUG] dose noting for me

### ISSUE THREAD

**Issue by Obazzi** [QWERTxD/BetterDiscordPlugins#276]
**Describe the Bug**
when i press the upload button next to the text bar, it dose the default discord behaviour

**To Reproduce**
press the upload button next to the text bar

**Expected Behaviour**
when i press the upload button next to the text bar, open the windows file picker

**Screenshots**
![image](https://user-images.githubusercontent.com/88412380/188295457-0fc6fc08-0c9e-4692-996c-71a8968d82b7.png)

**Discord Version**
Stable 145429 (57a0505)
BetterDiscord 1.6.3
Host 1.0.9006 Windows 10 64-Bit (10.0.19043)

**Additional Context**
is there a file in better discord that has the list of all my enabled add-ons? would be easier to modify to troubleshoot

**Comment by jaspwr** [comment]
I'm pretty sure this issue is caused by `options.length > 1` from this line because removing it fixes it
`if(!options || options.length > 1 || options[0]?.type !== "UPLOAD_A_FILE") return;`
I think this was written before this menu showed the options for slash commands or starting threads and I don't think there's any way to go about fixing it without making those options inaccessible so idk

**Comment by Obazzi** [comment]
> I'm pretty sure this issue is caused by `options.length > 1` from this line because removing it fixes it

Thanks! Seems to work now.

> I think this was written before this menu showed the options for slash commands or starting threads and I don't think there's any way to go about fixing it without making those options inaccessible so idk

I never create threads and to do slash commands I type `/`. I think this add-on should be fixed because, for a lot of people just like me, losing threads is worth it to be able to upload files normally.

**Comment by Obazzi** [comment]
Updated to v1.0.1 and it seems to work just like the manual fix. Thanks you! :)
